// import vant from 'vant'
// import 'vant/lib/index.css'
// Vue.use(vant)
import Vue from 'vue'
import 'vant/lib/index.css'
import { Uploader, List, Lazyload, Cell, CellGroup, Popup, Picker, DatetimePicker, Field, Form, Tab, Tabs, Checkbox, Dialog, ActionSheet, Rate, Icon, Search, Swipe, SwipeItem, Grid, GridItem, Button, Switch, Tabbar, TabbarItem, NavBar, Toast } from 'vant'
Vue.use(Cell)
Vue.use(Uploader)
Vue.use(List)
Vue.use(Lazyload)
Vue.use(CellGroup)
Vue.use(Popup)
Vue.use(Picker)
Vue.use(DatetimePicker)
Vue.use(Tab)
Vue.use(Field)
Vue.use(Form)
Vue.use(Tabs)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(Icon)
Vue.use(ActionSheet)
Vue.use(Rate)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(NavBar)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Tabbar)
Vue.use(TabbarItem)
